name: e_commerce
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.0
  firebase_core: ^1.10.2
  get: ^4.5.1
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  http: ^0.13.4
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/


